// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShop.Inventory.API.Infrastructure;

#nullable disable

namespace Inventory.API.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20260910074741_InventoryReliability")]
    partial class InventoryReliability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShop.IntegrationEventLogEF.IntegrationEventLogEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("TimesSent")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.ToTable("IntegrationEventLog", "inventory");
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.IncomingIntegrationEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId");

                    b.ToTable("incoming_integration_events", "inventory");
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.InventoryBalance", b =>
                {
                    b.Property<int>("SkuId")
                        .HasColumnType("integer")
                        .HasColumnName("sku_id");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("location_code");

                    b.Property<int>("MaxStock")
                        .HasColumnType("integer")
                        .HasColumnName("max_stock");

                    b.Property<int>("OnHand")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_point");

                    b.Property<int>("Reserved")
                        .HasColumnType("integer")
                        .HasColumnName("reserved");

                    b.Property<int>("SafetyStock")
                        .HasColumnType("integer")
                        .HasColumnName("safety_stock");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("SkuId", "LocationCode");

                    b.HasIndex("LocationCode", "SkuId")
                        .HasDatabaseName("ix_inventory_balances_location_sku");

                    b.ToTable("inventory_balances", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_balances_capacity", "on_hand <= max_stock");

                            t.HasCheckConstraint("ck_inventory_balances_max_stock", "max_stock >= reorder_point");

                            t.HasCheckConstraint("ck_inventory_balances_on_hand", "on_hand >= 0");

                            t.HasCheckConstraint("ck_inventory_balances_reorder_point", "reorder_point >= safety_stock");

                            t.HasCheckConstraint("ck_inventory_balances_reserved", "reserved >= 0");

                            t.HasCheckConstraint("ck_inventory_balances_reserved_on_hand", "reserved <= on_hand");

                            t.HasCheckConstraint("ck_inventory_balances_safety_stock", "safety_stock >= 0");
                        });
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.InventoryLocation", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("locations", "inventory");
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.InventoryMovement", b =>
                {
                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.Property<long>("BalanceVersionAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_version_after");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("location_code");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("movement_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("SkuId")
                        .HasColumnType("integer")
                        .HasColumnName("sku_id");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.HasKey("MovementId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_inventory_movements_order_id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_inventory_movements_recorded_at");

                    b.HasIndex("SkuId", "LocationCode", "OccurredAt")
                        .HasDatabaseName("ix_inventory_movements_sku_location_occurred_at");

                    b.HasIndex("SourceEventId", "SkuId", "LocationCode", "MovementType")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_movements_source_sku_location_type");

                    b.ToTable("inventory_movements", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movements_balance_version", "balance_version_after > 0");

                            t.HasCheckConstraint("ck_inventory_movements_quantity", "quantity <> 0");
                        });
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.InventoryReservation", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("SkuId")
                        .HasColumnType("integer")
                        .HasColumnName("sku_id");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("location_code");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("OrderId", "SkuId", "LocationCode");

                    b.HasIndex("SkuId", "LocationCode");

                    b.HasIndex("Status", "ReservedAt")
                        .HasDatabaseName("ix_inventory_reservations_status_reserved_at");

                    b.ToTable("inventory_reservations", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reservations_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.InventoryShadowCheck", b =>
                {
                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<bool?>("CatalogConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("catalog_confirmed");

                    b.Property<DateTime?>("CatalogObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("catalog_observed_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("details");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<bool>("InventoryConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("inventory_confirmed");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("location_code");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.HasKey("SourceEventId");

                    b.HasIndex("OrderId");

                    b.ToTable("inventory_shadow_checks", "inventory");
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.InventoryBalance", b =>
                {
                    b.HasOne("eShop.Inventory.API.Model.InventoryLocation", null)
                        .WithMany()
                        .HasForeignKey("LocationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.InventoryMovement", b =>
                {
                    b.HasOne("eShop.Inventory.API.Model.InventoryBalance", null)
                        .WithMany()
                        .HasForeignKey("SkuId", "LocationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Inventory.API.Model.InventoryReservation", b =>
                {
                    b.HasOne("eShop.Inventory.API.Model.InventoryBalance", null)
                        .WithMany()
                        .HasForeignKey("SkuId", "LocationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
